name: Build macOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install dependencies
        run: brew install libomp
      - name: Build
        run: ./BuildMacOS.sh